/**
 * Texte des Panels, Deutsch und Englisch mit denselben Schlüsseln
 * (tests/test_translations.py prüft das). Texte mit Zahlen sind Funktionen.
 */
export const STRINGS = {
  de: {
    title: "Geräte",
    search: "In allen Spalten suchen…",
    availability: "Verfügbarkeit",
    ofTotal: (n) => `von ${n} online`,
    linesOnline: (n) => `${n} online`,
    linesOffline: (n) => `${n} ausgefallen`,
    linesNoData: (n) => `${n} ohne Daten`,
    offlineNow: "Gerade ausgefallen",
    longest: (d) => `längster seit ${d}`,
    allOnline: "Alles online",
    allOnlineSub: "Kein Gerät ist gerade ausgefallen.",
    more: (n) => `+ ${n} weitere`,
    hints: "Hinweise",
    hintBattery: "Batterie niedrig",
    hintSignal: "Schwacher Empfang",
    hintUpdate: "Update verfügbar",
    hintNone: "Nichts zu tun.",
    all: "Alle",
    onlyProblems: "Nur Probleme",
    clearFilter: "Filter aufheben",
    connZigbee: "Zigbee",
    connZwave: "Z-Wave",
    connThread: "Thread",
    connMatter: "Matter",
    connBle: "Bluetooth",
    connWifi: "WLAN",
    connEthernet: "LAN",
    connNetwork: "Netzwerk",
    connCloud: "Cloud",
    connUnknown: "Unbekannt",
    groupOffline: "Ausgefallen",
    groupOfflineHint: "längste Dauer zuerst",
    groupNoData: "Keine Daten",
    groupNoDataHint: "keine Entität mit Zustand",
    groupOnline: "Online",
    colName: "Gerät",
    colStatus: "Status",
    colConnection: "Verbindung",
    colBattery: "Batterie",
    colIntegration: "Integration",
    colModel: "Hersteller / Modell",
    colSoftware: "Software",
    statusOnline: "Online",
    statusOffline: "ausgefallen",
    statusNoData: "Keine Daten",
    via: (name) => `über ${name}`,
    sinceRestart: "Mindestens: ausgefallen schon vor dem Neustart von Home Assistant",
    batteryLow: "niedrig",
    update: "Update",
    updateTo: (v) => `Update auf ${v} verfügbar`,
    dayUnit: "T.",
    hourUnit: "Std.",
    minuteUnit: "Min.",
    underMinute: "< 1 Min.",
    footer: (shown, total) => `${shown} von ${total} Geräten`,
    updatedAt: (t) => `Stand ${t}`,
    loading: "Geräte werden geladen…",
    empty: "Keine Geräte gefunden.",
    error: "Laden fehlgeschlagen:",
  },
  en: {
    title: "Devices",
    search: "Search all columns…",
    availability: "Availability",
    ofTotal: (n) => `of ${n} online`,
    linesOnline: (n) => `${n} online`,
    linesOffline: (n) => `${n} offline`,
    linesNoData: (n) => `${n} without data`,
    offlineNow: "Offline right now",
    longest: (d) => `longest for ${d}`,
    allOnline: "Everything online",
    allOnlineSub: "No device is offline right now.",
    more: (n) => `+ ${n} more`,
    hints: "Attention",
    hintBattery: "Low battery",
    hintSignal: "Weak signal",
    hintUpdate: "Update available",
    hintNone: "Nothing to do.",
    all: "All",
    onlyProblems: "Problems only",
    clearFilter: "Clear filter",
    connZigbee: "Zigbee",
    connZwave: "Z-Wave",
    connThread: "Thread",
    connMatter: "Matter",
    connBle: "Bluetooth",
    connWifi: "Wi-Fi",
    connEthernet: "LAN",
    connNetwork: "Network",
    connCloud: "Cloud",
    connUnknown: "Unknown",
    groupOffline: "Offline",
    groupOfflineHint: "longest first",
    groupNoData: "No data",
    groupNoDataHint: "no entity with a state",
    groupOnline: "Online",
    colName: "Device",
    colStatus: "Status",
    colConnection: "Connection",
    colBattery: "Battery",
    colIntegration: "Integration",
    colModel: "Manufacturer / model",
    colSoftware: "Software",
    statusOnline: "Online",
    statusOffline: "offline",
    statusNoData: "No data",
    via: (name) => `via ${name}`,
    sinceRestart: "At least: already offline before Home Assistant restarted",
    batteryLow: "low",
    update: "Update",
    updateTo: (v) => `Update to ${v} available`,
    dayUnit: "d",
    hourUnit: "h",
    minuteUnit: "min",
    underMinute: "< 1 min",
    footer: (shown, total) => `${shown} of ${total} devices`,
    updatedAt: (t) => `Updated ${t}`,
    loading: "Loading devices…",
    empty: "No devices found.",
    error: "Loading failed:",
  },
};

export function pickLang(hass) {
  const lang = String((hass && (hass.locale?.language || hass.language)) || "en").toLowerCase();
  return lang === "de" || lang.startsWith("de-") ? "de" : "en";
}
