/**
 * Texte des Panels, Deutsch und Englisch mit denselben Schlüsseln
 * (tests/test_translations.py prüft das). Texte mit Zahlen sind Funktionen.
 */
export const STRINGS = {
  de: {
    title: "Geräte",
    search: "In allen Spalten suchen…",
    searchClear: "Suche löschen",
    availability: "Verfügbarkeit",
    avg24: "Ø 24 Std.",
    pctNow: "jetzt",
    ofTotal: (n) => `von ${n} online`,
    linesOnline: (n) => `${n} stabil`,
    linesFlaky: (n) => `${n} instabil`,
    linesOffline: (n) => `${n} ausgefallen`,
    linesNoData: (n) => `${n} ohne Daten`,
    offlineNow: "Gerade ausgefallen",
    longest: (d) => `längster seit ${d}`,
    allOnline: "Alles online",
    stripTop: "Zurück zu den Kacheln",
    allOnlineSub: "Kein Gerät ist gerade ausgefallen.",
    more: (n) => `+ ${n} weitere`,
    pulseTitle: "Ausfall-Puls · 24 Std.",
    pulseNone: "Keine Unterbrüche in den letzten 24 Std.",
    pulseOpen: "Geräte mit Unterbrüchen zeigen",
    pulseWinTitle: "Unterbrüche in 24 Std.",
    pulseWinSub: (n, d, total) => `${n === 1 ? "1 Unterbruch" : `${n} Unterbrüche`} bei ${d === 1 ? "1 Gerät" : `${d} Geräten`} · zusammen ${total}`,
    pulseWinHint: "Tipp auf einen Zeitpunkt im Puls zeigt nur die Geräte, die dann weg waren.",
    pulseWinList: "Geräte · meiste Unterbrüche zuerst",
    pulseWinClear: "Zeitpunkt aufheben",
    pulseSummary: (n, d) => `${n === 1 ? "1 Unterbruch" : `${n} Unterbrüche`} bei ${d === 1 ? "1 Gerät" : `${d} Geräten`}`,
    pulseTip: (time, n) => `${time} · ${n === 1 ? "1 Gerät" : `${n} Geräte`} mit Unterbruch`,
    incidentTitle: (time) => `${time} · Sammelausfall`,
    incidentText: (n, integ) => (integ ? `${n} Geräte gleichzeitig, alle über ${integ}. Vermutlich liegt es an der Integration oder ihrem Hub.` : `${n} Geräte fielen gleichzeitig aus.`),
    now: "jetzt",
    today: "heute",
    hintBatteries: "Batterie",
    hintBattery: "Batterie niedrig",
    hintSignal: "Schwacher Empfang",
    hintNew: "Neu",
    newTag: "Neu",
    newTip: (at) => `Neu: in Home Assistant hinzugefügt ${at}`,
    added: "Hinzugefügt",
    hintUpdate: "Update verfügbar",
    all: "Alle",
    onlyProblems: "Nur Probleme",
    areaChip: "Bereich",
    areaTitle: "Bereiche",
    areaSub: "Für dich gespeichert. Eine Etage wählt alle ihre Bereiche.",
    areaSubMobile: "Für dich gespeichert · Handy und Desktop getrennt",
    areaSearch: "Bereich suchen",
    areaNoFloor: "Ohne Etage",
    areaNone: "Ohne Bereich",
    areaMany: (n) => `${n} Bereiche`,
    areaCount: (n, total) => `${n} von ${total} ${total === 1 ? "Bereich" : "Bereichen"}`,
    areaShowAll: "Alle zeigen",
    areaDone: "Fertig",
    areaClear: "Filter Bereich aufheben",
    areaNoMatch: "Kein Bereich gefunden.",
    areaEmpty: "In Home Assistant sind keine Bereiche angelegt.",
    integChip: "Integration",
    integTitle: "Integrationen",
    integSub: "Für dich gespeichert. Die Liste zeigt nur die Geräte der gewählten Integrationen.",
    integSearch: "Integration suchen",
    integNone: "Ohne Integration",
    integMany: (n) => `${n} Integrationen`,
    integCount: (n, total) => `${n} von ${total} ${total === 1 ? "Integration" : "Integrationen"}`,
    integShowAll: "Alle zeigen",
    integClear: "Filter Integration aufheben",
    integNoMatch: "Keine Integration gefunden.",
    integEmpty: "Es gibt keine Integrationen mit Geräten.",
    connZigbee: "Zigbee",
    connZwave: "Z-Wave",
    connThread: "Thread",
    connMatter: "Matter",
    connBle: "Bluetooth",
    connWifi: "WLAN",
    connEthernet: "LAN",
    connNetwork: "Netzwerk",
    connCloud: "Cloud",
    connUnknown: "Unbekannt",
    typeHub: "Hub / Bridge",
    typePhone: "Handy / Computer",
    typeNetwork: "Netzwerk",
    typeValve: "Ventil",
    typeEnergy: "Energie / Zähler",
    typeClimate: "Klima / Heizung",
    typeLock: "Schloss",
    typeCover: "Rollladen / Abdeckung",
    typeVacuum: "Roboter",
    typeCamera: "Kamera",
    typeAlarm: "Alarm / Sirene",
    typeMedia: "Medien",
    typeFan: "Ventilator",
    typeLight: "Licht",
    typeOutlet: "Steckdose",
    typeSwitch: "Schalter",
    typeMotion: "Bewegung / Präsenz",
    typeContact: "Tür / Fenster",
    typeSafety: "Rauch / Wasser / Gas",
    typeSensor: "Sensor",
    typeButton: "Taster",
    typeOther: "Sonstiges",
    groupOffline: "Ausgefallen",
    groupOfflineHint: "längste Dauer zuerst",
    groupFlaky: "Instabil",
    groupFlakyHint: (n) => `${n} oder mehr Unterbrüche in 24 Std.`,
    groupNoData: "Keine Daten",
    groupNoDataHint: "keine Entität mit Zustand",
    groupDisabled: "Deaktiviert",
    groupDisabledHint: "nicht überwacht",
    groupUnmonitored: "Nicht überwacht",
    groupUnmonitoredHint: "Integration auf \"Nicht überwachen\"",
    groupOnline: "Online",
    colName: "Gerät",
    colStatus: "Status",
    colConnection: "Verbindung",
    colType: "Typ",
    colIntegration: "Integration",
    colAvail: "Verfügbarkeit 24 Std.",
    colBattery: "Batterie",
    colModel: "Hersteller / Modell",
    colSoftware: "Software",
    colArea: "Bereich",
    colOutages: "Unterbrüche 24 Std.",
    colVia: "Hub / Bridge",
    viewBtn: "Spalten",
    viewTitle: "Ansicht",
    customizeTitle: "Anpassen",
    customizeSub: "Spalten der Liste · für dich gespeichert, getrennt vom Handy",
    customizeHint: "Auge: ein- oder ausblenden. Griff: in eine andere Reihenfolge ziehen.",
    restoreDefault: "Standard wiederherstellen",
    colHide: (c) => `${c} ausblenden`,
    colShowIt: (c) => `${c} einblenden`,
    viewSubMobile: "Handy · für dich gespeichert, getrennt vom Desktop",
    colFixed: "immer sichtbar",
    colDragHint: "Ziehen oder Pfeiltasten zum Verschieben",
    colDragMove: (label) => `Verschieben: ${label}`,
    viewDone: "Fertig",
    sortBy: "Sortieren nach",
    sortDefault: "Standard (Ausfälle zuerst)",
    sortSignal: "Empfang",
    sortName: "Name",
    sortDir: "Richtung",
    sortAsc: "aufsteigend",
    sortDesc: "absteigend",
    sortTip: (label) => `Sortieren nach ${label}`,
    viewDisplay: "Darstellung",
    viewGroupsOrList: "Gruppen oder eine Liste",
    viewGroups: "Gruppen",
    viewList: "Liste",
    viewGroupsNote: "Gruppen: Ausgefallene immer zuoberst, sortiert wird innerhalb der Gruppen.",
    viewFields: "Angaben auf der Karte",
    viewFieldsNote: "Was unter dem Namen steht, in dieser Reihenfolge. \"Verbindung\" ist die Zeile mit Funkart und Empfang bei ausgefallenen und instabilen Geräten.",
    fieldAvail: (pct) => `${pct} % verfügbar`,
    fieldSw: (v) => `Version ${v}`,
    statusOnline: "Online",
    statusOffline: "ausgefallen",
    statusOfflinePill: (d) => `Ausgefallen seit ${d}`,
    statusFlaky: "Instabil",
    statusNoData: "Keine Daten",
    statusDisabled: "Deaktiviert",
    statusUnmonitored: "Nicht überwacht",
    flakyOutages: (n) => `${n}× in 24 Std.`,
    via: (name) => `über ${name}`,
    sinceAtLeast: (t) => `Mindestens seit ${t}: Der genaue Beginn ist nicht bekannt, Home Assistant lief nicht oder überwachte das Gerät noch nicht.`,
    offlineSinceAt: (t) => `Ausgefallen seit ${t}`,
    batteryLow: "niedrig",
    update: "Update",
    updateTo: (v) => `Update auf ${v} verfügbar`,
    dayUnit: "T.",
    hourUnit: "Std.",
    minuteUnit: "Min.",
    underMinute: "< 1 Min.",
    footer: (shown, total) => `${shown} von ${total} Geräten`,
    updatedAt: (t) => `Stand ${t}`,
    openDetails: "Antippen für Details",
    loading: "Geräte werden geladen…",
    empty: "Keine Geräte gefunden.",
    error: "Laden fehlgeschlagen:",
    reconnecting: "Verbindung zu Home Assistant unterbrochen, neuer Versuch …",
    close: "Schliessen",
    openDevicePage: "HA-Geräteseite öffnen",
    secStats: "Statistik",
    tileAvail: "Verfügbarkeit 24 Std.",
    tileOutages7: "Unterbrüche 7 Tage",
    tileSignal: "Empfang",
    tileBattery: "Batterie",
    statOutages: (n, longest) => `${n === 1 ? "1 Unterbruch" : `${n} Unterbrüche`} · längster ${longest}`,
    statNoOutages: "keine Unterbrüche",
    statNoData: "noch keine Daten",
    pctWait: "Prozent ab 1 Std. Daten",
    statTotal: (d) => `zusammen ${d}`,
    tierNames: ["", "schwach", "mässig", "gut", "sehr gut"],
    secConnection: "Verbindung",
    connType: "Verbindungsart",
    viaLabel: "Verbunden über",
    secAi: "Einschätzung",
    secAiSettings: "KI-Einschätzung",
    aiButton: "Mit KI einschätzen",
    aiRetry: "Erneut versuchen",
    aiAgain: "Neu erstellen",
    aiWorking: "Die KI wertet die Angaben aus …",
    aiTitleDefault: "Einschätzung",
    aiBy: (source, at) => `Erstellt von "${source}" · ${at}`,
    aiNote: "Gesendet werden Name, Bereich und Werte dieses Geräts sowie Name und Werte von Geräten im selben Bereich, am selben Hub, vom selben Modell und weiterer ausgefallener Geräte derselben Integration, keine Schlüssel oder Zugangsdaten. Eine Einschätzung ist eine Vermutung.",
    aiError: (e) => `Einschätzung fehlgeschlagen: ${e}`,
    aiErr_disabled: "Die KI-Einschätzung ist in den Einstellungen ausgeschaltet.",
    aiErr_no_ai_task: "Keine KI-Aufgabe verfügbar. In Home Assistant eine KI-Aufgabe einrichten (Einstellungen → System → Allgemein) oder hier eine wählen.",
    aiErr_timeout: "Die KI hat nicht rechtzeitig geantwortet.",
    aiErr_failed: "Die KI-Aufgabe hat einen Fehler gemeldet. Details im Protokoll von Home Assistant.",
    aiErr_not_found: "Gerät nicht gefunden.",
    optAi: "Knopf \"Mit KI einschätzen\" zeigen",
    optAiShort: "Aus, bis eingeschaltet. Nur auf Knopfdruck, nie von selbst.",
    optAiInfo: "Das Panel schickt Name, Bereich und Werte eines einzelnen Geräts (Ausfälle, Batterie mit Verlauf der letzten 12 Monate, Empfang, Hub, Integration, Sammelausfälle) sowie Name und Werte von höchstens 15 Geräten im selben Bereich, Zahlen zu Geräten am selben Hub und vom selben Modell und Name und Dauer von höchstens 10 weiteren ausgefallenen Geräten derselben Integration an die KI-Aufgabe von Home Assistant. Keine Schlüssel, keine Zugangsdaten, keine IDs. Je nach Anbieter gehen die Daten in die Cloud und kosten pro Anfrage.",
    optAiTask: "KI-Aufgabe",
    optAiTaskShort: "Nutzt die KI-Aufgaben von Home Assistant (Einstellungen → System → Allgemein).",
    aiTaskDefault: "Standard von Home Assistant",
    aiNoTasks: "Keine KI-Aufgabe gefunden. Zuerst in Home Assistant eine einrichten.",
    sumAiOff: "Aus",
    sumAiPrompt: "Eigener Prompt",
    optAiExpert: "Profi-Modus",
    optAiExpertShort: "Den Prompt ansehen und anpassen",
    aiPromptTitle: "Prompt",
    aiPromptDefault: "Standard",
    aiPromptOwn: "Eigener",
    aiPromptEdit: "Bearbeiten …",
    aiPromptCopy: "Kopieren",
    aiPromptCopied: "Kopiert",
    aiPromptReset: "Standard",
    aiPromptPrivacy: "Der Prompt geht mit den Fakten des Geräts an den KI-Anbieter. Schlüssel, Zugangsdaten, IDs und Adressen sind nie dabei.",
    promptTitle: "Prompt bearbeiten",
    promptSubDefault: "Standard",
    promptSubOwn: "Eigener Prompt statt Standard",
    promptTabEdit: "Bearbeiten",
    promptTabPreview: "Vorschau",
    promptInsert: (v) => `${v} einfügen`,
    promptVarInfo: (v) => ({
      "{language}": "Sprache der Antwort",
      "{facts}": "Alle Fakten des Geräts",
      "{facts_device}": "Gerät: Name, Status, Typ, Bereich, Hersteller, Modell, Software, Verbindung, Ausfalldauer",
      "{facts_history}": "Verlauf: Verfügbarkeit 24 Std. und 7 Tage, Sammelausfälle",
      "{facts_battery}": "Batterie: Stand und Prognose",
      "{facts_signal}": "Empfang",
      "{facts_integration}": "Integration: andere Geräte und ausgefallene",
      "{facts_area}": "Bereich: Geräte im selben Raum, gleicher Funkstandard",
      "{facts_hub}": "Hub: Zustand und Geräte am selben Hub",
      "{facts_model}": "Modell: Geräte desselben Modells",
    })[v] || "",
    promptVarsHint: "{facts} enthält alles. Statt {facts} lassen sich einzelne Gruppen einsetzen, um Umfang und Reihenfolge selbst zu bestimmen.",
    promptCount: (n, max) => `${n} von ${max} Zeichen`,
    promptHeadline: "Die erste Zeile der Antwort zeigt das Panel als Überschrift. Verlangt der Prompt ein anderes Format, steht die ganze Antwort als Text.",
    promptInsertDefault: "Standard einfügen",
    promptApply: "Übernehmen",
    promptCancel: "Abbrechen",
    promptDevice: "Gerät",
    promptNoDevice: "Kein Gerät für die Vorschau.",
    promptPreviewLoading: "Vorschau wird erstellt …",
    promptPreviewError: "Vorschau nicht möglich:",
    promptPreviewNote: "So geht der Prompt raus, mit den Fakten dieses Geräts. Nur diese Angaben verlassen das Haus; Entitätsnamen, IDs, Adressen und Schlüssel sind nie dabei. Die Vorschau schickt nichts an die KI.",
    promptErrNoFacts: "Der Prompt braucht {facts} oder mindestens eine Gruppe wie {facts_device}, sonst bekommt die KI keine Angaben zum Gerät.",
    promptErrUnknown: (v) => `Unbekannter Platzhalter ${v}. Erlaubt sind {language}, {facts} und die Gruppen {facts_device}, {facts_history}, {facts_battery}, {facts_signal}, {facts_integration}, {facts_area}, {facts_hub}, {facts_model}.`,
    promptErrLong: (max) => `Der Prompt ist zu lang (höchstens ${max} Zeichen).`,
    sumAiOn: (task) => `Ein${task ? ` · ${task}` : " · Standard von Home Assistant"}`,
    threadRole: "Thread-Rolle",
    roleRouter: "Router",
    roleRouterHint: "leitet Nachrichten weiter",
    roleEnd: "Endgerät",
    roleEndHint: "hängt an einem Router",
    roleSleepy: "Schlafendes Endgerät",
    roleSleepyHint: "meldet sich nur zeitweise",
    threadNet: "Netz",
    threadNetHint: "Netzname aus der Diagnose",
    integrationLabel: "Integration",
    entryStates: {
      setup_error: "Einrichtung fehlgeschlagen",
      setup_retry: "wartet auf neuen Versuch",
      setup_in_progress: "wird eingerichtet",
      not_loaded: "nicht geladen",
      failed_unload: "Entladen fehlgeschlagen",
      migration_error: "Migration fehlgeschlagen",
    },
    secDevice: "Gerät",
    typeLabel: "Typ",
    typeAuto: (t) => `Automatisch: ${t}`,
    typeManual: "von Hand gesetzt",
    connAutoInteg: (t) => `Wie Integration: ${t}`,
    connByInteg: "für die ganze Integration festgelegt",
    typeSaveError: "Typ konnte nicht gespeichert werden:",
    connSaveError: "Verbindungsart konnte nicht gespeichert werden:",
    manufacturer: "Hersteller",
    model: "Modell",
    software: "Software",
    hardware: "Hardware",
    area: "Bereich",
    secEntities: (n) => `Entitäten · ${n}`,
    liveness: "Lebenszeichen",
    livenessHint: "Markierte Entitäten zeigen, ob das Gerät lebt.",
    unavailable: "nicht verfügbar",
    loadingDetail: "Lädt…",
    deviceGone: "Dieses Gerät gibt es nicht mehr oder es wird nicht mehr überwacht.",
    statTitle: "Verfügbarkeit",
    ranges: { "24h": "24 Std.", "7d": "7 Tage", "30d": "30 Tage", "90d": "3 Monate", "180d": "6 Monate", "365d": "12 Monate" },
    batHistoryHint: "Verlauf",
    batNoData: "Keine Daten für diesen Zeitraum.",
    batSince: (delta, date) => `${delta > 0 ? "+" : delta < 0 ? "−" : "±"}${Math.abs(delta)} % seit dem Wechsel am ${date}`,
    batPerDay: (v) => `etwa ${v} % pro Tag`,
    batFcTitle: "Prognose",
    batFcLeft: (d) => `Reicht noch etwa ${d}`,
    batFcTarget: (pct, date) => `bis ${pct} % (Warnschwelle), um den ${date}`,
    batFcTargetZero: (date) => `bis leer (0 %), um den ${date}`,
    batFcRange: (lo, hi) => `Spanne ${lo} bis ${hi}`,
    batFcRangeMin: (lo) => `mindestens ${lo}`,
    batFcConf: (c) => `Sicherheit: ${c === "high" ? "hoch" : c === "medium" ? "mittel" : "gering"}`,
    batFcBasisChange: (date, n) => `Gerechnet seit dem Wechsel am ${date} (${n} Tage)`,
    batFcBasisAll: (n) => `Gerechnet über ${n} Tage`,
    batFcRate: (v) => `−${v} % pro Monat`,
    batFcAccel: "Der Verlauf wird steiler: die Prognose ist eher zu optimistisch.",
    batFcShortChange: (n, min) => `Noch zu wenig Verlauf seit dem Wechsel (${n} von ${min} Tagen) für eine Prognose.`,
    batFcShortAll: (n, min) => `Noch zu wenig Verlauf (${n} von ${min} Tagen) für eine Prognose.`,
    batFcFlat: "Der Stand sinkt kaum: keine Prognose möglich.",
    batFcReached: (pct) => `Die Warnschwelle von ${pct} % ist erreicht.`,
    batFcReachedZero: "Die Batterie ist leer.",
    batFcNote: "Näherung aus dem bisherigen Verlauf, ohne KI.",
    batFcDays: (n) => `${n} ${n === 1 ? "Tag" : "Tage"}`,
    batFcMonths: (n) => `${n} ${n === 1 ? "Monat" : "Monate"}`,
    batFcYears: (n) => `${n} Jahre`,
    batFcOver5: "mehr als 5 Jahre",
    batMinMax: (lo, hi) => `Tiefster ${lo} % · höchster ${hi} %`,
    batThreshold: (p) => `Schwach ab ${p} %`,
    batChange: "Wechsel",
    batChanged: "Batterie gewechselt",
    batSrcStats: "Aus dem Recorder (Langzeitstatistik: Stundenwerte, auch über 10 Tage hinaus).",
    batSrcStatsDay: "Aus dem Recorder (Langzeitstatistik: Tagesmittel, auch über 10 Tage hinaus).",
    batSrcHistory: "Aus dem Verlauf des Recorders.",
    batSrcHistoryLong: "Aus dem Verlauf des Recorders, so weit er Daten hat (Standard 10 Tage): Der Sensor führt keine Langzeitstatistik.",
    batSrcNone: "Ohne Recorder gibt es keinen Verlauf, nur den aktuellen Stand.",
    sigFacts: (median, worst, best) => `Median ${median} · schlechtester ${worst} · bester ${best}`,
    sigWeakLine: (v) => `Schwach unter ${v}`,
    sigLegendMedian: "Median",
    sigLegendSpan: "Spanne schlechtester bis bester Wert",
    sigSrcHistory: "Aus dem Verlauf des Recorders (Sensor des Geräts).",
    sigSrcHistoryLong: "Aus dem Verlauf des Recorders, so weit er Daten hat (Standard 10 Tage): Der Sensor führt keine Langzeitstatistik.",
    sigSrcStats: "Aus dem Recorder (Langzeitstatistik: Stundenmittel des Sensors).",
    sigSrcLog: (since) => `Vom Panel aufgezeichnet, seit ${since}: Median je 5 Min., ab 7 Tagen je Stunde. Lücken: Gerät ausgefallen oder nicht empfangen.`,
    sigSrcLogEmpty: "Das Panel zeichnet den Empfang dieses Geräts selbst auf (die Integration liefert keinen Sensor dafür). Erste Werte nach wenigen Minuten.",
    sigSrcNone: "Für den Empfang dieses Geräts gibt es keinen Verlauf.",
    sigSrcNotRecorded: "Der Recorder zeichnet den Sensor nicht auf (in seiner Konfiguration ausgeschlossen), deshalb zeichnet ihn das Panel selbst auf.",
    sigSrcSoon: "Erste Werte nach wenigen Minuten.",
    histSteady: (time) => `Wert unverändert seit ${time}.`,
    availOnline: "Online",
    availOffline: "Ausgefallen",
    availNone: "Keine Daten",
    availNever: "die ganze Zeit ausgefallen",
    availAlways: "keine Unterbrüche",
    availOutages: (n) => (n === 1 ? "1 Unterbruch" : `${n} Unterbrüche`),
    availTotal: (d) => `zusammen ${d}`,
    availLongest: (d) => `längster ${d}`,
    availSince: (t) => `Daten seit ${t}`,
    availOngoing: "läuft",
    availMore: (n) => `+ ${n} weitere`,
    daysTitle: "Unterbrüche pro Tag",
    settingsBtn: "Einstellungen",
    settingsTitle: "Einstellungen",
    settingsSub: "Device Panel · gilt für alle Benutzer",
    settingsLoading: "Einstellungen werden geladen…",
    settingsLoadError: "Einstellungen konnten nicht geladen werden:",
    settingsSaveError: "Speichern fehlgeschlagen:",
    settingsChanged: "geändert",
    settingsChanges: (n) => (n === 1 ? "1 Änderung" : `${n} Änderungen`),
    settingsCancel: "Abbrechen",
    settingsSave: "Speichern",
    settingsSaving: "Speichert…",
    settingsSavedShort: "Gespeichert",
    settingsInfo: "Mehr erfahren",
    settingsRange: (min, max) => `Erlaubt: ${min} bis ${max}`,
    optOfflineAfter: "Ausgefallen nach",
    optOfflineAfterInfo:
      "Ein Gerät gilt als ausgefallen, wenn es so lange kein Lebenszeichen gibt: Ein Verbindungssensor meldet getrennt, sonst sind alle normalen Entitäten nicht verfügbar. Der Ausfall beginnt trotzdem beim echten Zeitpunkt, an dem das Gerät nicht mehr antwortete. Gilt ab dem Speichern; bisherige Unterbrüche bleiben, wie sie sind.",
    optFlaky: "Instabil ab",
    unitOutages: "Unterbrüche",
    optFlakyShort: "in 24 Std., bei einem Gerät, das gerade online ist.",
    optFlakyInfo: "Solche Geräte stehen in der Gruppe \"Instabil\" und unter \"Nur Probleme\".",
    optGrace: "Anlaufphase nach dem Start",
    optGraceShort: "Wer in dieser Zeit zurückkommt, hatte keinen Unterbruch.",
    optGraceInfo:
      "Nach einem Start von Home Assistant brauchen Integrationen oft einige Minuten, bis ihre Geräte wieder verfügbar sind. Wer danach noch fehlt, gilt ab dem Start als ausgefallen. Zeit, in der Home Assistant nicht lief, zählt nie als Ausfall, sondern als \"keine Daten\". 0 schaltet die Anlaufphase aus.",
    sumDisplay: (service, disabled) =>
      service === disabled
        ? `Dienst-Geräte und deaktivierte Geräte ${service ? "angezeigt" : "ausgeblendet"}`
        : `Dienst-Geräte ${service ? "angezeigt" : "ausgeblendet"} · deaktivierte ${disabled ? "angezeigt" : "ausgeblendet"}`,
    sumChipsHidden: (n) => (n === 1 ? "1 Filter-Chip ausgeblendet" : `${n} Filter-Chips ausgeblendet`),
    optChips: "Filter-Chips der Verbindungsart",
    chipsIntro: "Welche Chips der Verbindungsart über der Liste stehen und in welcher Reihenfolge (am Griff ziehen); die Geräte bleiben sichtbar. Gilt für alle Benutzer.",
    chipsOtherTitle: "Weitere Chips",
    chipsConnTitle: "Verbindungsart",
    chipsOtherIntro: "Welche übrigen Chips über der Liste stehen; \"Alle\" bleibt immer. Ein ausgeblendeter Chip hebt seinen Filter auf, die Geräte bleiben sichtbar. Gilt für alle Benutzer.",
    chipOther: {
      area: ["Bereich", "Filter nach Bereich"],
      integration: ["Integration", "Filter nach Integration"],
      problems: ["Nur Probleme", "Nur ausgefallene und instabile Geräte"],
      batteries: ["Batterie", "Alle Geräte mit Batterie"],
      battery: ["Batterie niedrig", "Geräte mit schwacher Batterie"],
      signal: ["Schwacher Empfang", "Geräte mit schwachem Empfang"],
      update: ["Update verfügbar", "Geräte mit verfügbarem Update"],
      override: ["Eigene Einstellung", "Geräte mit eigenen Einstellungen"],
      new: ["Neu", "In den letzten 3 Tagen hinzugefügt"],
    },
    sumChipsOrder: "Chips in eigener Reihenfolge",
    chipsOrderReset: "Nach Anzahl sortieren",
    dragHint: "Ziehen oder mit den Pfeiltasten verschieben",
    dragMove: (label) => `Verschieben: ${label}`,
    optShowService: "Dienst-Geräte anzeigen",
    optShowServiceShort: "Dienste einer Integration, z. B. Sonne, Wettervorhersage oder Add-ons.",
    optShowServiceInfo: "Dienst-Geräte sind keine echten Geräte. Angezeigt werden sie wie alle anderen überwacht und zählen in der Statistik mit.",
    optShowDisabled: "Deaktivierte Geräte anzeigen",
    optShowDisabledShort: "Eigene Gruppe am Ende der Liste, nicht überwacht.",
    optPushMode: "Zeitpunkt der Push-Meldung",
    pushModeInstant: "Sofort",
    pushModeDaily: "Einmal täglich um",
    optPushModeShortInstant: "Sobald ein Gerät unter die Schwelle fällt.",
    optPushModeShortDaily: (time) => `Eine Sammelmeldung um ${time}; Ausfall-Meldungen betrifft das nicht.`,
    optPushDaily: "Die Tagesmeldung enthält",
    dailyNew: "Neu betroffene Geräte",
    dailyAll: "Alle schwachen Geräte",
    optPushDailyShort: "Neu betroffen: seit der letzten Tagesmeldung schwach geworden. Alle: jeden Tag als Erinnerung, bis die Batterie gewechselt ist.",
    timeError: "Uhrzeit HH:MM",
    optBatteryLow: "Schwach ab",
    unitPercent: "%",
    optBatteryPush: "Push-Meldung",
    optBatteryPushShort: "Einmal pro Gerät, wenn es unter die Schwelle fällt.",
    optBatteryPushInfo:
      "Erneut erst, wenn die Batterie zwischendurch 5 Punkte über der Schwelle war, z. B. nach einem Batteriewechsel. Fallen mehr als 3 Geräte gleichzeitig darunter, kommt eine Sammelmeldung. Beim Einschalten kommen die gerade betroffenen Geräte einmal.",
    optBatteryPersistent: "Anhaltende Benachrichtigung",
    optBatteryPersistentShort: "Eine Meldung in Home Assistant mit allen betroffenen Geräten, bis alle wieder darüber sind.",
    optBatteryPersistentInfo:
      "Erscheint unter den Benachrichtigungen von Home Assistant (Glocke). Wer sie wegklickt, hat Ruhe, bis ein weiteres Gerät dazukommt oder Home Assistant neu startet.",
    offlineNone: "Nicht überwachen",
    offlineMin: (m) => (m % 60 === 0 ? `${m / 60} Std.` : `${m} Min.`),
    optDelay: "Erst melden nach",
    optFields: "Inhalt der Ausfall-Meldung",
    optFieldsShort: "Welche Angaben die Meldung \"Ausgefallen: …\" enthält; der Gerätename steht im Titel.",
    optFieldsNote1: "\"Batterie zuletzt\" und \"Empfang zuletzt\" nennen den letzten bekannten Stand des ausgefallenen Geräts, \"Offline seit\" den Beginn des Ausfalls.",
    optFieldsNote2: "Gilt nur für die Ausfall-Meldung. Die Meldung bei schwacher Batterie hat einen eigenen Inhalt im Reiter \"Batterie\".",
    fieldArea: "Bereich",
    fieldIntegration: "Integration",
    fieldConnection: "Verbindungsart",
    fieldSince: "Offline seit",
    fieldSignal: "Empfang zuletzt",
    fieldBattery: "Batterie zuletzt",
    fieldModel: "Hersteller / Modell",
    pvLabel: "Vorschau",
    pvSample: "Beispielgerät",
    pvApp: "Home Assistant · jetzt",
    pvTitle: (name) => `Ausgefallen: ${name}`,
    pvSince: (time) => `seit ${time}`,
    pvSignal: (v) => `Empfang zuletzt ${v}`,
    pvBattery: (v) => `Batterie ${v}`,
    pvOpen: "Öffnen",
    pvMute: "24 Std. stumm",
    pvNote: "Knöpfe in der Companion-App; \"24 Std. stumm\" schaltet die Meldungen für das Gerät einen Tag ab.",
    pvExample: "Kursiv: Beispielwert, weil das gezeigte Gerät diese Angabe nicht hat. In der echten Meldung fehlt sie dann.",
    pvSampleBattery: "64 %",
    pvSampleSignal: "-72 dBm",
    pvSampleModel: "Beispiel AG Modell A",
    pvSampleConn: "Zigbee",
    optOutagePersistentShort: "Eine Sammelmeldung in Home Assistant, solange Geräte ausgefallen sind; die Batterie hat ihre eigene im Reiter \"Batterie\".",
    devNotifyMuted: (time) => `Stumm bis ${time}`,
    // "meldet …": Die Arten sind eingeschaltete Meldungen, kein Zustand.
    optOutage: "Ausfall melden",
    optOutageShort: "Sobald \"Erst melden nach\" um ist, an das Ziel im Reiter \"Übersicht\".",
    optOnline: "Wieder online melden",
    optOnlineShort: "Entwarnung, sobald das Gerät zurück ist, mit der Dauer des Ausfalls.",
    optGroup: "Sammelausfall zusammenfassen",
    optGroupShort: "Ab 3 Geräten gleichzeitig eine Meldung mit vermuteter Ursache statt vieler.",
    secNotifyDevice: "Einstellungen für dieses Gerät",
    devBattery: "Batterie-Warnung",
    devBatDefault: (pct) => `Globaler Wert (${pct === "off" ? "aus" : `${pct} %`})`,
    devBatOwn: "Eigene Schwelle",
    devBatOff: "Aus",
    devBatLow: "Schwach ab",
    devBatShort: (pct, integ) =>
      pct === "off"
        ? `Globaler Wert: aus (Batterie-Warnung für ${integ} ausgeschaltet). Eine eigene Schwelle schaltet sie für dieses Gerät wieder ein.`
        : `Globaler Wert: ${pct} %${integ ? ` (eigene Schwelle von ${integ})` : ""}. "Aus" schaltet Markierung, Push und anhaltende Benachrichtigung für dieses Gerät ab.`,
    devSignal: "Empfang-Warnung",
    devSigDefault: (std) => `Globaler Wert (unter ${std})`,
    devSigOwn: "Eigene Schwelle",
    devSigOff: "Aus",
    devSigLow: "Schwach unter",
    devSigShort: (now) =>
      `${now ? `Heute ${now}. ` : ""}Für Geräte, die immer schwachen Empfang haben: eine eigene Schwelle (vorgeschlagen etwas unter dem heutigen Wert) oder "Aus". Markierung und Filter "Schwacher Empfang" folgen.`,
    devNotify: "Ausfall- und Online-Meldungen",
    devNotifyOn: "Globale Einstellung",
    devNotifyOff: "Aus für dieses Gerät",
    devNotifyShort: "\"Aus\" für Geräte, die oft absichtlich offline sind (z. B. ein Ladegerät). Das Gerät wird weiter überwacht.",
    hintOverride: "Eigene Einstellung",
    ovrBatOwnTip: (v, g) => `Eigene Batterie-Schwelle: ${v} % (global ${g === "off" ? "aus" : `${g} %`})`,
    ovrBatOffTip: "Batterie-Warnung aus (nur dieses Gerät)",
    ovrNotifyOffTip: "Ausfall- und Online-Meldungen aus (nur dieses Gerät)",
    ovrBatTitle: "Eigene Werte auf Geräten",
    ovrBatShort: "Diese Geräte weichen vom globalen Wert ab (eingestellt im Geräte-Popup). Zurückgesetzt wird beim Speichern.",
    ovrBatEmpty: "Keine. Eigene Werte setzt man im Geräte-Popup.",
    ovrNotifyTitle: "Meldungen auf Geräten ausgeschaltet",
    ovrNotifyShort: "Für diese Geräte sind Ausfall- und Online-Meldungen aus (eingestellt im Geräte-Popup). Zurückgesetzt wird beim Speichern.",
    ovrNotifyEmpty: "Keine. Ausschalten lassen sie sich im Geräte-Popup.",
    ovrTimeOffTip: "Nicht überwacht (nur dieses Gerät)",
    ovrTimeOwnTip: (v) => `Eigenes "Ausgefallen nach": ${v}`,
    ovrTimeTitle: "Eigenes \"Ausgefallen nach\" auf Geräten",
    ovrTimeShort: "Diese Geräte haben eine eigene Zeit oder sind auf \"Nicht überwachen\" gestellt (eingestellt im Geräte-Popup). Zurückgesetzt gilt wieder die Integration bzw. der globale Wert; beim Speichern.",
    ovrTimeEmpty: "Keine. Eigene Zeiten setzt man im Geräte-Popup.",
    ovrToInteg: "→ Integration",
    devOffline: "Ausgefallen nach",
    devOffInteg: (v) => `Wie Integration (${v})`,
    devOffGlobal: (v) => `Globaler Wert (${v})`,
    devOffOwn: "Eigene Zeit",
    devOffNone: "Nicht überwachen",
    devOffShort: "Zeit ohne Lebenszeichen, bis das Gerät als ausgefallen gilt. \"Nicht überwachen\": das Gerät bleibt sichtbar, ohne Ausfälle, Statistik und Meldungen. Das Gerät geht vor der Integration.",
    devBatInteg: (pct) => `Wie Integration (${pct === "off" ? "aus" : `${pct} %`})`,
    devNotifyInteg: "Wie Integration",
    originStandard: "Standard",
    originDevice: "Gerät",
    originIntegration: (name) => `Integration ${name}`,
    originDefaultWould: (v) => `Standard wäre ${v}`,
    originNotify: (push, persistent) => `Push ${push ? "an" : "aus"} · Anhaltend ${persistent ? "an" : "aus"}`,
    originNotifyOff: "Für dieses Gerät aus",
    ovrSigOwnTip: (v) => `Eigene Empfang-Schwelle: schwach unter ${v}`,
    ovrSigOffTip: "Empfang-Warnung aus (nur dieses Gerät)",
    ovrSigTitle: "Empfang-Warnung auf Geräten",
    ovrSigShort: "Diese Geräte haben eine eigene Empfang-Warnung (eingestellt im Geräte-Popup). Zurückgesetzt gilt wieder der globale Wert; beim Speichern.",
    ovrSigEmpty: "Keine. Eigene Werte setzt man im Geräte-Popup.",
    ovrSigValue: (v) => `unter ${v}`,
    ovrConnTip: (kind, base) => `Verbindungsart von Hand: ${kind} (sonst ${base})`,
    ovrConnTitle: "Verbindungsart von Hand auf Geräten",
    ovrConnShort: "Diese Geräte haben eine Verbindungsart von Hand (eingestellt im Geräte-Popup). Zurückgesetzt gilt wieder die Integration bzw. die Erkennung; beim Speichern.",
    ovrConnEmpty: "Keine. Von Hand setzt man sie im Geräte-Popup.",
    ovrToAuto: "→ automatisch",
    ovrResetAll: "Alle zurücksetzen",
    ovrReset: (name) => `Zurücksetzen: ${name}`,
    ovrUndo: (name) => `Nicht zurücksetzen: ${name}`,
    ovrOff: "Aus",
    ovrToGlobal: "→ global",
    ovrHidden: "ausgeblendet",
    devSaveError: "Konnte nicht gespeichert werden:",
    optNotifyTarget: "Ziel",
    optNotifyTargetShort: "notify-Dienst oder -Entität, z. B. die Companion-App.",
    optNotifyTargetInfo:
      "Alle Push-Meldungen von Device Panel gehen an dieses Ziel; auch Gruppen (z. B. notify.familie) gehen. Eine notify-Entität bekommt nur Titel und Text, ohne Bild und Klickziel.",
    notifyNone: "Kein Ziel (keine Push-Meldungen)",
    notifyEntity: (v) => `${v} (Entität)`,
    notifyMissing: (v) => `${v} (nicht gefunden)`,
    optClick: "Tipp auf Meldung öffnet",
    optClickShort: "Wohin ein Tipp auf eine Meldung zu einem Gerät führt.",
    clickPanel: "Gerät im Panel",
    clickDevice: "Geräteseite von Home Assistant",
    // Überwachung und Meldungen (seit 0.34.0, docs/mockups/notify-v3).
    secMonitor: "Überwachung und Meldungen",
    sumMonitor: ({ offline, push, delay, battery, batPush, daily }) =>
      `Ausfall nach ${offline} Min.${push ? `, Push nach ${delay} Min.` : ", ohne Push"} · Batterie schwach ab ${battery} %${batPush ? (daily ? `, Push täglich ${daily}` : ", Push sofort") : ", ohne Push"}`,
    tabOverview: "Übersicht",
    tabOutage: "Ausfall",
    tabBattery: "Batterie",
    tabInteg: "Integrationen",
    laneOutage: "Ausfall",
    laneBattery: "Batterie schwach",
    laneEdit: "Ändern ›",
    tlGone: "Gerät weg",
    tlOffline: "im Panel ausgefallen",
    tlPush: "Push \"Ausgefallen\"",
    tlBoth: "ausgefallen und Push",
    tlNoPush: "Kein Push",
    tlNoTarget: "kein Ziel gewählt",
    tlSwitchedOff: "ausgeschaltet",
    tlIntegOff: "für die Integration aus",
    tlLow: (pct) => `bis ${pct} %`,
    tlRed: "im Panel rot",
    tlInstant: "sofort",
    tlInstantSub: "Push, einmal pro Gerät",
    tlDaily: (time) => `täglich ${time}`,
    tlDailyNew: "Push, neu betroffene",
    tlDailyAll: "Push, alle schwachen",
    tlNote: "Beide Zeiten zählen ab Beginn des Ausfalls, sie werden nicht addiert. \"Ausgefallen nach\" gilt auch für das Panel; \"Erst melden nach\" kann nicht kürzer sein.",
    tlBatNote: "\"Schwach ab\" gilt auch für die rote Markierung im Panel. Sofort: einmal pro Gerät, wenn es darunter fällt. Täglich: eine Sammelmeldung zur gewählten Zeit.",
    delayShort: (min) => `"Erst melden nach" muss mindestens ${min} Min. sein ("Ausgefallen nach"). Vorher gilt ein Gerät nicht als ausgefallen.`,
    chipPush: "Push",
    chipPersistent: "Anhaltend",
    chipOnline: "Wieder online",
    chipGroup: "Sammelausfall",
    diffLabel: "Abweichend:",
    diffNone: "Keine Abweichungen",
    diffInteg: (n) => (n === 1 ? "1 Integration" : `${n} Integrationen`),
    diffDev: (n) => (n === 1 ? "1 Gerät" : `${n} Geräte`),
    grpDetect: "Erkennung",
    grpNotify: "Meldung",
    grpDiff: "Abweichungen",
    grpOutage: "Ausfall",
    grpBattery: "Batterie",
    diffIntegTitle: (n) => (n === 1 ? "1 Integration weicht ab" : n ? `${n} Integrationen weichen ab` : "Integrationen"),
    diffIntegGo: "Integrationen ›",
    diffIntegNone: "Alle Integrationen wie hier eingestellt.",
    noTargetWarn: "Ohne Ziel kommt kein Push. Ziel wählen: Reiter \"Übersicht\".",
    optPersistent: "Anhaltende Benachrichtigung",
    optBatFields: "Inhalt der Batterie-Meldung",
    optBatFieldsShort: "Welche Angaben die Meldung \"Batterie schwach: …\" enthält; der Gerätename steht im Titel.",
    bfBattery: "Stand",
    pvBatTitle: (name) => `Batterie schwach: ${name}`,
    pvBatNote: "Fallen mehr als 3 Geräte gleichzeitig darunter, oder als Tagesmeldung: eine Sammelmeldung mit Name und Stand je Gerät, die übrigen Angaben in Klammern.",
    pvSampleArea: "Flur",
    pvSampleInteg: "Zigbee",
    integListIntro: "Gilt für alle Geräte der Integration; ein Gerät kann im Geräte-Popup abweichen. Ausgeblendete Integrationen stehen nur im Abschnitt \"Integrationen\".",
    filterAll: (n) => `Alle ${n}`,
    filterOwn: (n) => `Abweichend ${n}`,
    integNone: "Keine Integrationen.",
    integNoneOwn: "Keine Integration weicht ab.",
    integStandard: "Standard",
    integUnmon: "Nicht überwacht",
    integDevs: (n, b) => `${n === 1 ? "1 Gerät" : `${n} Geräte`}${b ? ` · ${b} mit Batterie` : ""}`,
    diffOutage: (after, flags) => (after ? [`Ausfall nach ${after}`, ...flags].join(", ") : `Ausfall ${flags.join(", ")}`),
    diffNoPush: "ohne Push",
    diffNoPers: "ohne Anhaltend",
    diffBattery: (pct, off, noPush) => (off ? "Batterie-Warnung aus" : pct != null ? `Batterie ${pct} %${noPush ? ", ohne Push" : ""}` : "Batterie ohne Push"),
    integBack: "Alle Integrationen",
    optMonitor: "Überwachen",
    optMonitorShort: "Aus: Die Geräte bleiben im Panel, ohne Ausfälle, Batterie-Warnung, Statistik und Meldungen.",
    integUnmonInfo: "Nicht überwacht: keine Ausfälle, keine Batterie-Warnung, keine Statistik und keine Meldungen. Die Geräte stehen weiter im Panel, mit dem Hinweis \"Nicht überwacht\". Ganz ausblenden: Abschnitt \"Integrationen\".",
    optPushOutage: "Push bei Ausfall",
    optBatPush: "Push bei schwacher Batterie",
    integOffDefault: (v) => `Standard (${v})`,
    integBatDefault: (v) => `Standard (${v} %)`,
    originOwn: "Eigene",
    originBatPushOff: "Push für die Integration aus",
    integPushLater: (v) => `Push erst nach ${v}: Vorher gilt ein Gerät dieser Integration nicht als ausgefallen.`,
    integPushGlobalOff: "Push bei Ausfall ist für alle aus (Reiter \"Ausfall\").",
    integBatPushGlobalOff: "Push bei schwacher Batterie ist für alle aus (Reiter \"Batterie\").",
    integDevTitle: "Geräte mit eigener Einstellung",
    ovrKindOffline: (v) => `Ausgefallen nach ${v}`,
    ovrKindUnmon: "Nicht überwacht",
    ovrKindNotify: "Meldungen aus",
    ovrKindBattery: (v) => (v === "off" ? "Batterie-Warnung aus" : `Batterie ${v} %`),
    integReset: "Alles auf Standard",
    integIntroShow: "Ausgeblendete Integrationen zeigt das Panel nicht, und ihre Geräte werden nicht überwacht.",
    integGoto: "Überwachen und Melden pro Integration:",
    integGotoLink: "Überwachung und Meldungen › Integrationen",
    secIntegrations: "Integrationen",
    secDevices: "Geräte im Panel",
    secLook: "Darstellung",
    subTypes: "Typen",
    subDevs: "Geräte",
    subConn: "Verbindungsart",
    subChips: "Filter-Chips",
    sumConnAuto: "Automatisch erkannt",
    sumConnInteg: (n) => (n === 1 ? "1 Integration festgelegt" : `${n} Integrationen festgelegt`),
    connIntegTitle: "Verbindungsart pro Integration",
    connIntegShort: "Gilt für alle Geräte der Integration statt der Erkennung; eine am Gerät von Hand gesetzte Verbindungsart geht vor. Gilt für alle Benutzer.",
    connIntegAuto: "Automatisch",
    connIntegDevices: (n, detected) => `${n === 1 ? "1 Gerät" : `${n} Geräte`}${detected ? ` · erkannt: ${detected}` : ""}`,
    sumDevHidden: (i, t, g) =>
      `${[i && (i === 1 ? "1 Integration" : `${i} Integrationen`), t && (t === 1 ? "1 Typ" : `${t} Typen`), g && (g === 1 ? "1 Gerät" : `${g} Geräte`)].filter(Boolean).join(", ")} ausgeblendet`,
    colShow: "Anzeigen",
    toggleAll: "Alle umschalten",
    devicesCount: (n) => (n === 1 ? "1 Gerät" : `${n} Geräte`),
    hideIntro: "Ausgeblendete Geräte zeigt das Panel nicht, und sie werden nicht überwacht (keine Ausfälle, kein Verlauf).",
    typesIntro: "Den Typ eines einzelnen Geräts änderst du in seinem Popup.",
    typesEmpty: "ohne Geräte",
    hiddenIntro: "Ausgeblendete Geräte stehen nicht in der Liste und werden nicht überwacht (keine Ausfälle, keine Meldungen). Gilt für alle Benutzer.",
    hiddenEmpty: 'Kein Gerät ausgeblendet. Ein Gerät blendest du in seinem Popup mit "Gerät ausblenden" aus.',
    hiddenShowAll: "Alle einblenden",
    hideDevice: "Gerät ausblenden",
    hiddenToast: (name) => `${name} ausgeblendet`,
    shownToast: (name) => `${name} wieder eingeblendet`,
    undo: "Rückgängig",
    hideError: "Ausblenden fehlgeschlagen:",
    unhideError: "Einblenden fehlgeschlagen:",
    secUpdates: "Updates",
    sumUpdatesOn: "Tägliche Prüfung · neue Version unter \"Reparaturen\"",
    sumUpdatesOff: "Keine automatische Prüfung",
    optUpdateCheck: "Täglich nach Updates suchen",
    optUpdateCheckShort: "Meldet eine neue Version unter Einstellungen → Reparaturen.",
    optUpdateCheckInfo:
      "Fragt einmal täglich die veröffentlichten Releases auf GitHub ab, die erste Prüfung zufällig 5–65 Minuten nach dem Start. Ergänzt HACS, das nur alle paar Tage prüft; wer die doppelte Meldung nicht möchte, schaltet es aus. Vorabversionen werden dort nie gemeldet.",
    verName: (v) => `Device Panel ${v}`,
    verCurrent: "Aktuell",
    verChecked: (rel) => `zuletzt geprüft ${rel}`,
    verCheck: "Nach Updates suchen",
    verChecking: "Prüft…",
    verCheckingSub: "Suche nach Updates…",
    verCheckError: "Prüfung fehlgeschlagen:",
    verRateLimit: "GitHub-Abfragelimit für diese Internetverbindung erreicht (60 pro Stunde). Später erneut versuchen.",
    verAvailable: (v) => `Version ${v} verfügbar`,
    verBeta: "Beta",
    verInstalled: (v) => `Installiert: ${v}`,
    verPreShort: "Vorabversion",
    verPreToggle: "Vorabversionen anzeigen",
    verPreToggleShort: "Auch Beta-Versionen zum Testen anbieten. Gilt für alle Benutzer.",
    verPreHint:
      "HACS installiert Vorabversionen nur, wenn bei dieser Integration \"Pre-release\" eingeschaltet ist: im HACS-Gerät die Entität \"Pre-release\" aktivieren und einschalten.",
    verPreHintLink: "HACS-Gerät öffnen",
    verPreHintEnable:
      "HACS installiert Vorabversionen nur, wenn bei dieser Integration \"Pre-release\" eingeschaltet ist. Das Panel kann das für dich erledigen: Es aktiviert die Entität in HACS und schaltet sie ein. HACS lädt dabei kurz neu (etwa 30 Sekunden). Schaltest du \"Vorabversionen anzeigen\" später aus, wird sie wieder ausgeschaltet.",
    verPreEnable: "In HACS freischalten",
    verPreEnabling: "Wird freigeschaltet … (bis 30 s)",
    verPreEnableError: "Freischalten fehlgeschlagen:",
    verPreEnableTimeout: "HACS hat die Entität nicht rechtzeitig bereitgestellt. Bitte im HACS-Gerät prüfen.",
    verInstalledVia: (v, hacs) => `Installiert: ${v}${hacs ? " · über HACS" : ""}`,
    verNoHacs: "Installation über HACS oder manuell (siehe Release Notes).",
    verReleaseNotes: "Release Notes",
    verUpdate: "Aktualisieren",
    verInstalling: (v) => `Wird aktualisiert auf ${v}…`,
    verInstallingSub: "HACS lädt die neue Version herunter",
    verInstallError: "Aktualisieren fehlgeschlagen:",
    verHacsSyncing: "Wird mit HACS abgeglichen …",
    verHacsPending:
      "HACS kennt diese Version noch nicht. \"Nach Updates suchen\" lässt HACS die Versionen neu laden; sonst später erneut versuchen.",
    verRestartNeeded: (v) => `${v} installiert – Neustart nötig`,
    verRestartSub: "Aktiv wird die neue Version erst nach einem Neustart von Home Assistant.",
    verRestart: "Jetzt neu starten",
    verRestartConfirm: "Home Assistant jetzt neu starten? Alle Integrationen sind dabei kurz nicht verfügbar.",
    verRestarting: "Home Assistant startet neu…",
  },
  en: {
    title: "Devices",
    search: "Search all columns…",
    searchClear: "Clear search",
    availability: "Availability",
    avg24: "avg. 24 h",
    pctNow: "now",
    ofTotal: (n) => `of ${n} online`,
    linesOnline: (n) => `${n} stable`,
    linesFlaky: (n) => `${n} unstable`,
    linesOffline: (n) => `${n} offline`,
    linesNoData: (n) => `${n} without data`,
    offlineNow: "Offline right now",
    longest: (d) => `longest for ${d}`,
    allOnline: "Everything online",
    stripTop: "Back to the tiles",
    allOnlineSub: "No device is offline right now.",
    more: (n) => `+ ${n} more`,
    pulseTitle: "Outage pulse · 24 h",
    pulseNone: "No outages in the last 24 hours.",
    pulseOpen: "Show devices with outages",
    pulseWinTitle: "Outages in 24 h",
    pulseWinSub: (n, d, total) => `${n === 1 ? "1 outage" : `${n} outages`} on ${d === 1 ? "1 device" : `${d} devices`} · ${total} in total`,
    pulseWinHint: "Tap a point in the pulse to show only the devices that were offline then.",
    pulseWinList: "Devices · most outages first",
    pulseWinClear: "Clear point in time",
    pulseSummary: (n, d) => `${n === 1 ? "1 outage" : `${n} outages`} on ${d === 1 ? "1 device" : `${d} devices`}`,
    pulseTip: (time, n) => `${time} · ${n === 1 ? "1 device" : `${n} devices`} with an outage`,
    incidentTitle: (time) => `${time} · Group outage`,
    incidentText: (n, integ) => (integ ? `${n} devices at once, all via ${integ}. Most likely the integration or its hub.` : `${n} devices went offline at once.`),
    now: "now",
    today: "today",
    hintBatteries: "Battery",
    hintBattery: "Low battery",
    hintSignal: "Weak signal",
    hintNew: "New",
    newTag: "New",
    newTip: (at) => `New: added to Home Assistant ${at}`,
    added: "Added",
    hintUpdate: "Update available",
    all: "All",
    onlyProblems: "Problems only",
    areaChip: "Area",
    areaTitle: "Areas",
    areaSub: "Saved for you. A floor selects all its areas.",
    areaSubMobile: "Saved for you · phone and desktop separately",
    areaSearch: "Search areas",
    areaNoFloor: "No floor",
    areaNone: "No area",
    areaMany: (n) => `${n} areas`,
    areaCount: (n, total) => `${n} of ${total} ${total === 1 ? "area" : "areas"}`,
    areaShowAll: "Show all",
    areaDone: "Done",
    areaClear: "Clear area filter",
    areaNoMatch: "No area found.",
    areaEmpty: "No areas are set up in Home Assistant.",
    integChip: "Integration",
    integTitle: "Integrations",
    integSub: "Saved for you. The list shows only the devices of the selected integrations.",
    integSearch: "Search integrations",
    integNone: "No integration",
    integMany: (n) => `${n} integrations`,
    integCount: (n, total) => `${n} of ${total} ${total === 1 ? "integration" : "integrations"}`,
    integShowAll: "Show all",
    integClear: "Clear integration filter",
    integNoMatch: "No integration found.",
    integEmpty: "There are no integrations with devices.",
    connZigbee: "Zigbee",
    connZwave: "Z-Wave",
    connThread: "Thread",
    connMatter: "Matter",
    connBle: "Bluetooth",
    connWifi: "Wi-Fi",
    connEthernet: "LAN",
    connNetwork: "Network",
    connCloud: "Cloud",
    connUnknown: "Unknown",
    typeHub: "Hub / bridge",
    typePhone: "Phone / computer",
    typeNetwork: "Network",
    typeValve: "Valve",
    typeEnergy: "Energy / meter",
    typeClimate: "Climate / heating",
    typeLock: "Lock",
    typeCover: "Cover / blind",
    typeVacuum: "Robot",
    typeCamera: "Camera",
    typeAlarm: "Alarm / siren",
    typeMedia: "Media",
    typeFan: "Fan",
    typeLight: "Light",
    typeOutlet: "Outlet",
    typeSwitch: "Switch",
    typeMotion: "Motion / presence",
    typeContact: "Door / window",
    typeSafety: "Smoke / leak / gas",
    typeSensor: "Sensor",
    typeButton: "Button",
    typeOther: "Other",
    groupOffline: "Offline",
    groupOfflineHint: "longest first",
    groupFlaky: "Unstable",
    groupFlakyHint: (n) => `${n} or more outages in 24 h`,
    groupNoData: "No data",
    groupNoDataHint: "no entity with a state",
    groupDisabled: "Disabled",
    groupDisabledHint: "not monitored",
    groupUnmonitored: "Not monitored",
    groupUnmonitoredHint: "integration set to \"Don't monitor\"",
    groupOnline: "Online",
    colName: "Device",
    colStatus: "Status",
    colConnection: "Connection",
    colType: "Type",
    colIntegration: "Integration",
    colAvail: "Availability 24 h",
    colBattery: "Battery",
    colModel: "Manufacturer / model",
    colSoftware: "Software",
    colArea: "Area",
    colOutages: "Outages 24 h",
    colVia: "Hub / bridge",
    viewBtn: "Columns",
    viewTitle: "View",
    customizeTitle: "Customize",
    customizeSub: "Columns of the list · saved for you, separate from the phone",
    customizeHint: "Eye: show or hide. Handle: drag into a different order.",
    restoreDefault: "Restore default",
    colHide: (c) => `Hide ${c}`,
    colShowIt: (c) => `Show ${c}`,
    viewSubMobile: "Phone · saved for you, separate from the desktop",
    colFixed: "always visible",
    colDragHint: "Drag or use the arrow keys to move",
    colDragMove: (label) => `Move: ${label}`,
    viewDone: "Done",
    sortBy: "Sort by",
    sortDefault: "Default (offline first)",
    sortSignal: "Signal",
    sortName: "Name",
    sortDir: "Direction",
    sortAsc: "ascending",
    sortDesc: "descending",
    sortTip: (label) => `Sort by ${label}`,
    viewDisplay: "Display",
    viewGroupsOrList: "Groups or one list",
    viewGroups: "Groups",
    viewList: "List",
    viewGroupsNote: "Groups: offline devices always on top, sorting applies within the groups.",
    viewFields: "Details on the card",
    viewFieldsNote: "What is shown below the name, in this order. \"Connection\" is the line with radio type and signal for offline and unstable devices.",
    fieldAvail: (pct) => `${pct} % available`,
    fieldSw: (v) => `Version ${v}`,
    statusOnline: "Online",
    statusOffline: "offline",
    statusOfflinePill: (d) => `Offline for ${d}`,
    statusFlaky: "Unstable",
    statusNoData: "No data",
    statusDisabled: "Disabled",
    statusUnmonitored: "Not monitored",
    flakyOutages: (n) => `${n}× in 24 h`,
    via: (name) => `via ${name}`,
    sinceAtLeast: (t) => `At least since ${t}: the exact start is unknown, Home Assistant was not running or not watching the device yet.`,
    offlineSinceAt: (t) => `Offline since ${t}`,
    batteryLow: "low",
    update: "Update",
    updateTo: (v) => `Update to ${v} available`,
    dayUnit: "d",
    hourUnit: "h",
    minuteUnit: "min",
    underMinute: "< 1 min",
    footer: (shown, total) => `${shown} of ${total} devices`,
    updatedAt: (t) => `Updated ${t}`,
    openDetails: "Tap for details",
    loading: "Loading devices…",
    empty: "No devices found.",
    error: "Loading failed:",
    reconnecting: "Connection to Home Assistant interrupted, trying again …",
    close: "Close",
    openDevicePage: "Open device page",
    secStats: "Statistics",
    tileAvail: "Availability 24 h",
    tileOutages7: "Outages 7 days",
    tileSignal: "Signal",
    tileBattery: "Battery",
    statOutages: (n, longest) => `${n === 1 ? "1 outage" : `${n} outages`} · longest ${longest}`,
    statNoOutages: "no outages",
    statNoData: "no data yet",
    pctWait: "Percent after 1 h of data",
    statTotal: (d) => `${d} in total`,
    tierNames: ["", "weak", "fair", "good", "excellent"],
    secConnection: "Connection",
    connType: "Connection type",
    viaLabel: "Connected via",
    secAi: "Assessment",
    secAiSettings: "AI assessment",
    aiButton: "Assess with AI",
    aiRetry: "Try again",
    aiAgain: "Create again",
    aiWorking: "The AI is analysing the details …",
    aiTitleDefault: "Assessment",
    aiBy: (source, at) => `Created by "${source}" · ${at}`,
    aiNote: "Name, area and values of this device and name and values of devices in the same area, on the same hub, of the same model and other offline devices of the same integration are sent, no keys or credentials. An assessment is a guess.",
    aiError: (e) => `Assessment failed: ${e}`,
    aiErr_disabled: "The AI assessment is switched off in the settings.",
    aiErr_no_ai_task: "No AI task available. Set one up in Home Assistant (Settings → System → General) or choose one here.",
    aiErr_timeout: "The AI did not answer in time.",
    aiErr_failed: "The AI task reported an error. See the Home Assistant log for details.",
    aiErr_not_found: "Device not found.",
    optAi: "Show the button \"Assess with AI\"",
    optAiShort: "Off until switched on. Only on a button press, never on its own.",
    optAiInfo: "The panel sends name, area and values of a single device (outages, battery with the last 12 months, signal, hub, integration, mass outages) plus name and values of at most 15 devices in the same area, counts for devices on the same hub and of the same model, and name and duration of at most 10 other offline devices of the same integration to the AI task of Home Assistant. No keys, no credentials, no IDs. Depending on the provider the data goes to the cloud and costs per request.",
    optAiTask: "AI task",
    optAiTaskShort: "Uses the AI tasks of Home Assistant (Settings → System → General).",
    aiTaskDefault: "Default of Home Assistant",
    aiNoTasks: "No AI task found. Set one up in Home Assistant first.",
    sumAiOff: "Off",
    sumAiPrompt: "Own prompt",
    optAiExpert: "Expert mode",
    optAiExpertShort: "View and adjust the prompt",
    aiPromptTitle: "Prompt",
    aiPromptDefault: "Default",
    aiPromptOwn: "Own",
    aiPromptEdit: "Edit …",
    aiPromptCopy: "Copy",
    aiPromptCopied: "Copied",
    aiPromptReset: "Default",
    aiPromptPrivacy: "The prompt goes to the AI provider together with the facts of the device. Keys, credentials, IDs and addresses are never included.",
    promptTitle: "Edit prompt",
    promptSubDefault: "Default",
    promptSubOwn: "Own prompt instead of the default",
    promptTabEdit: "Edit",
    promptTabPreview: "Preview",
    promptInsert: (v) => `Insert ${v}`,
    promptVarInfo: (v) => ({
      "{language}": "Language of the answer",
      "{facts}": "All facts of the device",
      "{facts_device}": "Device: name, status, type, area, manufacturer, model, software, connection, time offline",
      "{facts_history}": "History: availability 24 h and 7 days, mass outages",
      "{facts_battery}": "Battery: level and forecast",
      "{facts_signal}": "Signal",
      "{facts_integration}": "Integration: other devices and offline ones",
      "{facts_area}": "Area: devices in the same room, same radio standard",
      "{facts_hub}": "Hub: state and devices on the same hub",
      "{facts_model}": "Model: devices of the same model",
    })[v] || "",
    promptVarsHint: "{facts} contains everything. Instead of {facts} you can insert single groups to choose scope and order yourself.",
    promptCount: (n, max) => `${n} of ${max} characters`,
    promptHeadline: "The panel shows the first line of the answer as the headline. If the prompt asks for another format, the whole answer is shown as text.",
    promptInsertDefault: "Insert default",
    promptApply: "Apply",
    promptCancel: "Cancel",
    promptDevice: "Device",
    promptNoDevice: "No device for the preview.",
    promptPreviewLoading: "Creating the preview …",
    promptPreviewError: "Preview not possible:",
    promptPreviewNote: "This is what goes out, with the facts of this device. Only these details leave the house; entity names, IDs, addresses and keys are never included. The preview sends nothing to the AI.",
    promptErrNoFacts: "The prompt needs {facts} or at least one group such as {facts_device}, otherwise the AI gets no details about the device.",
    promptErrUnknown: (v) => `Unknown placeholder ${v}. Allowed are {language}, {facts} and the groups {facts_device}, {facts_history}, {facts_battery}, {facts_signal}, {facts_integration}, {facts_area}, {facts_hub}, {facts_model}.`,
    promptErrLong: (max) => `The prompt is too long (at most ${max} characters).`,
    sumAiOn: (task) => `On${task ? ` · ${task}` : " · Home Assistant default"}`,
    threadRole: "Thread role",
    roleRouter: "Router",
    roleRouterHint: "forwards messages",
    roleEnd: "End device",
    roleEndHint: "attached to a router",
    roleSleepy: "Sleepy end device",
    roleSleepyHint: "checks in only now and then",
    threadNet: "Network",
    threadNetHint: "network name from the diagnostics",
    integrationLabel: "Integration",
    entryStates: {
      setup_error: "setup failed",
      setup_retry: "waiting to retry",
      setup_in_progress: "setting up",
      not_loaded: "not loaded",
      failed_unload: "unload failed",
      migration_error: "migration failed",
    },
    secDevice: "Device",
    typeLabel: "Type",
    typeAuto: (t) => `Automatic: ${t}`,
    typeManual: "set by hand",
    connAutoInteg: (t) => `Same as integration: ${t}`,
    connByInteg: "set for the whole integration",
    typeSaveError: "Could not save the type:",
    connSaveError: "Could not save the connection type:",
    manufacturer: "Manufacturer",
    model: "Model",
    software: "Software",
    hardware: "Hardware",
    area: "Area",
    secEntities: (n) => `Entities · ${n}`,
    liveness: "Sign of life",
    livenessHint: "Marked entities show whether the device is alive.",
    unavailable: "unavailable",
    loadingDetail: "Loading…",
    deviceGone: "This device no longer exists or is no longer monitored.",
    statTitle: "Availability",
    ranges: { "24h": "24 h", "7d": "7 days", "30d": "30 days", "90d": "3 months", "180d": "6 months", "365d": "12 months" },
    batHistoryHint: "History",
    batNoData: "No data for this period.",
    batSince: (delta, date) => `${delta > 0 ? "+" : delta < 0 ? "−" : "±"}${Math.abs(delta)} % since the change on ${date}`,
    batPerDay: (v) => `about ${v} % per day`,
    batFcTitle: "Forecast",
    batFcLeft: (d) => `Lasts about ${d} more`,
    batFcTarget: (pct, date) => `until ${pct} % (warning threshold), around ${date}`,
    batFcTargetZero: (date) => `until empty (0 %), around ${date}`,
    batFcRange: (lo, hi) => `Range ${lo} to ${hi}`,
    batFcRangeMin: (lo) => `at least ${lo}`,
    batFcConf: (c) => `Confidence: ${c === "high" ? "high" : c === "medium" ? "medium" : "low"}`,
    batFcBasisChange: (date, n) => `Based on the time since the change on ${date} (${n} days)`,
    batFcBasisAll: (n) => `Based on ${n} days`,
    batFcRate: (v) => `−${v} % per month`,
    batFcAccel: "The drop is getting steeper: the forecast is probably too optimistic.",
    batFcShortChange: (n, min) => `Not enough history since the change yet (${n} of ${min} days) for a forecast.`,
    batFcShortAll: (n, min) => `Not enough history yet (${n} of ${min} days) for a forecast.`,
    batFcFlat: "The level barely drops: no forecast possible.",
    batFcReached: (pct) => `The warning threshold of ${pct} % has been reached.`,
    batFcReachedZero: "The battery is empty.",
    batFcNote: "Estimate from the history so far, without AI.",
    batFcDays: (n) => `${n} ${n === 1 ? "day" : "days"}`,
    batFcMonths: (n) => `${n} ${n === 1 ? "month" : "months"}`,
    batFcYears: (n) => `${n} years`,
    batFcOver5: "more than 5 years",
    batMinMax: (lo, hi) => `Lowest ${lo} % · highest ${hi} %`,
    batThreshold: (p) => `Low from ${p} %`,
    batChange: "Change",
    batChanged: "Battery changed",
    batSrcStats: "From the recorder (long-term statistics: hourly values, also beyond 10 days).",
    batSrcStatsDay: "From the recorder (long-term statistics: daily means, also beyond 10 days).",
    batSrcHistory: "From the recorder history.",
    batSrcHistoryLong: "From the recorder history, as far as it has data (default 10 days): the sensor keeps no long-term statistics.",
    batSrcNone: "Without the recorder there is no history, only the current level.",
    sigFacts: (median, worst, best) => `Median ${median} · worst ${worst} · best ${best}`,
    sigWeakLine: (v) => `Weak below ${v}`,
    sigLegendMedian: "Median",
    sigLegendSpan: "Range from worst to best value",
    sigSrcHistory: "From the recorder history (sensor of the device).",
    sigSrcHistoryLong: "From the recorder history, as far as it has data (default 10 days): the sensor keeps no long-term statistics.",
    sigSrcStats: "From the recorder (long-term statistics: hourly mean of the sensor).",
    sigSrcLog: (since) => `Recorded by the panel since ${since}: median per 5 min, from 7 days per hour. Gaps: device offline or not received.`,
    sigSrcLogEmpty: "The panel records the signal of this device itself (the integration provides no sensor for it). First values after a few minutes.",
    sigSrcNone: "There is no history for the signal of this device.",
    sigSrcNotRecorded: "The recorder does not record the sensor (excluded in its configuration), so the panel records it itself.",
    sigSrcSoon: "First values after a few minutes.",
    histSteady: (time) => `Value unchanged since ${time}.`,
    availOnline: "Online",
    availOffline: "Offline",
    availNone: "No data",
    availNever: "offline the whole time",
    availAlways: "no outages",
    availOutages: (n) => (n === 1 ? "1 outage" : `${n} outages`),
    availTotal: (d) => `${d} in total`,
    availLongest: (d) => `longest ${d}`,
    availSince: (t) => `data since ${t}`,
    availOngoing: "ongoing",
    availMore: (n) => `+ ${n} more`,
    daysTitle: "Outages per day",
    settingsBtn: "Settings",
    settingsTitle: "Settings",
    settingsSub: "Device Panel · applies to all users",
    settingsLoading: "Loading settings…",
    settingsLoadError: "Could not load the settings:",
    settingsSaveError: "Saving failed:",
    settingsChanged: "changed",
    settingsChanges: (n) => (n === 1 ? "1 change" : `${n} changes`),
    settingsCancel: "Cancel",
    settingsSave: "Save",
    settingsSaving: "Saving…",
    settingsSavedShort: "Saved",
    settingsInfo: "Learn more",
    settingsRange: (min, max) => `Allowed: ${min} to ${max}`,
    optOfflineAfter: "Offline after",
    optOfflineAfterInfo:
      "A device counts as offline when it gives no sign of life for this long: a connectivity sensor reports disconnected, otherwise all regular entities are unavailable. The outage still starts at the real moment the device stopped responding. Applies from saving; earlier outages stay as they are.",
    optFlaky: "Unstable from",
    unitOutages: "outages",
    optFlakyShort: "in 24 h, for a device that is online right now.",
    optFlakyInfo: "Such devices are listed in the group \"Unstable\" and under \"Problems only\".",
    optGrace: "Grace period after start",
    optGraceShort: "Devices returning within this time had no outage.",
    optGraceInfo:
      "After Home Assistant starts, integrations often need a few minutes until their devices are available again. Devices still missing afterwards count as offline from the start. Time when Home Assistant was not running never counts as an outage but as \"no data\". 0 turns the grace period off.",
    sumDisplay: (service, disabled) =>
      service === disabled
        ? `Service devices and disabled devices ${service ? "shown" : "hidden"}`
        : `Service devices ${service ? "shown" : "hidden"} · disabled ${disabled ? "shown" : "hidden"}`,
    sumChipsHidden: (n) => (n === 1 ? "1 filter chip hidden" : `${n} filter chips hidden`),
    optChips: "Filter chips of the connection type",
    chipsIntro: "Which connection type chips appear above the list and in which order (drag by the handle); the devices stay visible. Applies to all users.",
    chipsOtherTitle: "Other chips",
    chipsConnTitle: "Connection type",
    chipsOtherIntro: "Which other chips appear above the list; \"All\" always stays. A hidden chip clears its filter, the devices stay visible. Applies to all users.",
    chipOther: {
      area: ["Area", "Filter by area"],
      integration: ["Integration", "Filter by integration"],
      problems: ["Problems only", "Only offline and unstable devices"],
      batteries: ["Battery", "All devices with a battery"],
      battery: ["Low battery", "Devices with a weak battery"],
      signal: ["Weak signal", "Devices with a weak signal"],
      update: ["Update available", "Devices with an update available"],
      override: ["Own setting", "Devices with own settings"],
      new: ["New", "Added in the last 3 days"],
    },
    sumChipsOrder: "chips in own order",
    chipsOrderReset: "Sort by number",
    dragHint: "Drag or move with the arrow keys",
    dragMove: (label) => `Move: ${label}`,
    optShowService: "Show service devices",
    optShowServiceShort: "Services of an integration, e.g. sun, weather forecast or add-ons.",
    optShowServiceInfo: "Service devices are not real devices. When shown, they are monitored like all others and count in the statistics.",
    optShowDisabled: "Show disabled devices",
    optShowDisabledShort: "Own group at the end of the list, not monitored.",
    optPushMode: "Time of the push notification",
    pushModeInstant: "Immediately",
    pushModeDaily: "Once a day at",
    optPushModeShortInstant: "As soon as a device drops below the threshold.",
    optPushModeShortDaily: (time) => `One summary at ${time}; outage notifications are not affected.`,
    optPushDaily: "The daily notification lists",
    dailyNew: "Newly affected devices",
    dailyAll: "All devices with a low battery",
    optPushDailyShort: "Newly affected: became low since the last daily notification. All: every day as a reminder until the battery is replaced.",
    timeError: "Time HH:MM",
    optBatteryLow: "Low from",
    unitPercent: "%",
    optBatteryPush: "Push notification",
    optBatteryPushShort: "Once per device when it drops below the threshold.",
    optBatteryPushInfo:
      "Again only after the battery was 5 points above the threshold in between, e.g. after a battery change. If more than 3 devices drop below at the same time, one summary is sent. When switched on, the devices affected right now are reported once.",
    optBatteryPersistent: "Persistent notification",
    optBatteryPersistentShort: "One notification in Home Assistant listing all affected devices until all are above again.",
    optBatteryPersistentInfo:
      "Appears under the Home Assistant notifications (bell). Dismissing it keeps it away until another device is affected or Home Assistant restarts.",
    offlineNone: "Don't monitor",
    offlineMin: (m) => (m % 60 === 0 ? `${m / 60} h` : `${m} min`),
    optDelay: "Report only after",
    optFields: "Content of the outage notification",
    optFieldsShort: "Which details the notification \"Offline: …\" contains; the device name is in the title.",
    optFieldsNote1: "\"Last battery level\" and \"Last signal\" give the last known value of the device that went offline, \"Offline since\" the start of the outage.",
    optFieldsNote2: "Applies to the outage notification only. The low battery notification has its own content in the tab \"Battery\".",
    fieldArea: "Area",
    fieldIntegration: "Integration",
    fieldConnection: "Connection type",
    fieldSince: "Offline since",
    fieldSignal: "Last signal",
    fieldBattery: "Last battery level",
    fieldModel: "Manufacturer / model",
    pvLabel: "Preview",
    pvSample: "Sample device",
    pvApp: "Home Assistant · now",
    pvTitle: (name) => `Offline: ${name}`,
    pvSince: (time) => `since ${time}`,
    pvSignal: (v) => `last signal ${v}`,
    pvBattery: (v) => `battery ${v}`,
    pvOpen: "Open",
    pvMute: "Mute 24 h",
    pvNote: "Buttons in the companion app; \"Mute 24 h\" turns off the notifications for the device for a day.",
    pvExample: "Italic: example value, because the device shown has no such detail. The real notification then leaves it out.",
    pvSampleBattery: "64 %",
    pvSampleSignal: "-72 dBm",
    pvSampleModel: "Example Inc. Model A",
    pvSampleConn: "Zigbee",
    optOutagePersistentShort: "One notification in Home Assistant as long as devices are offline; the battery has its own in the tab \"Battery\".",
    devNotifyMuted: (time) => `Muted until ${time}`,
    optOutage: "Report outages",
    optOutageShort: "Once \"Report only after\" has passed, to the target in the tab \"Overview\".",
    optOnline: "Report back online",
    optOnlineShort: "All clear as soon as the device is back, with the duration of the outage.",
    optGroup: "Combine group outages",
    optGroupShort: "From 3 devices at once one notification with the probable cause instead of many.",
    secNotifyDevice: "Settings for this device",
    devBattery: "Battery warning",
    devBatDefault: (pct) => `Global value (${pct === "off" ? "off" : `${pct} %`})`,
    devBatOwn: "Own threshold",
    devBatOff: "Off",
    devBatLow: "Low from",
    devBatShort: (pct, integ) =>
      pct === "off"
        ? `Global value: off (battery warning turned off for ${integ}). An own threshold turns it back on for this device.`
        : `Global value: ${pct} %${integ ? ` (own threshold of ${integ})` : ""}. "Off" turns off the marking, push and persistent notification for this device.`,
    devSignal: "Weak signal warning",
    devSigDefault: (std) => `Global value (below ${std})`,
    devSigOwn: "Own threshold",
    devSigOff: "Off",
    devSigLow: "Weak below",
    devSigShort: (now) =>
      `${now ? `Now ${now}. ` : ""}For devices that always have a weak signal: an own threshold (suggested a little below today's value) or "Off". Marking and the filter "Weak signal" follow.`,
    devNotify: "Outage and online notifications",
    devNotifyOn: "Global setting",
    devNotifyOff: "Off for this device",
    devNotifyShort: "\"Off\" for devices that are often offline on purpose (e.g. a charger). The device is still monitored.",
    hintOverride: "Own setting",
    ovrBatOwnTip: (v, g) => `Own battery threshold: ${v} % (global ${g === "off" ? "off" : `${g} %`})`,
    ovrBatOffTip: "Battery warning off (this device only)",
    ovrNotifyOffTip: "Outage and online notifications off (this device only)",
    ovrBatTitle: "Own values on devices",
    ovrBatShort: "These devices differ from the global value (set in the device pop-up). They are reset when you save.",
    ovrBatEmpty: "None. Own values are set in the device pop-up.",
    ovrNotifyTitle: "Notifications switched off on devices",
    ovrNotifyShort: "Outage and online notifications are off for these devices (set in the device pop-up). They are reset when you save.",
    ovrNotifyEmpty: "None. They can be switched off in the device pop-up.",
    ovrTimeOffTip: "Not monitored (this device only)",
    ovrTimeOwnTip: (v) => `Own "Offline after": ${v}`,
    ovrTimeTitle: "Own \"Offline after\" on devices",
    ovrTimeShort: "These devices have their own time or are set to \"Don't monitor\" (set in the device pop-up). Once reset, the integration or the global value applies again; when you save.",
    ovrTimeEmpty: "None. Own times are set in the device pop-up.",
    ovrToInteg: "→ integration",
    devOffline: "Offline after",
    devOffInteg: (v) => `Same as integration (${v})`,
    devOffGlobal: (v) => `Global value (${v})`,
    devOffOwn: "Own time",
    devOffNone: "Don't monitor",
    devOffShort: "Time without a sign of life before the device counts as offline. \"Don't monitor\": the device stays visible, without outages, statistics and notifications. The device takes precedence over the integration.",
    devBatInteg: (pct) => `Same as integration (${pct === "off" ? "off" : `${pct} %`})`,
    devNotifyInteg: "Same as integration",
    originStandard: "Default",
    originDevice: "Device",
    originIntegration: (name) => `Integration ${name}`,
    originDefaultWould: (v) => `Default would be ${v}`,
    originNotify: (push, persistent) => `Push ${push ? "on" : "off"} · Persistent ${persistent ? "on" : "off"}`,
    originNotifyOff: "Off for this device",
    ovrSigOwnTip: (v) => `Own signal threshold: weak below ${v}`,
    ovrSigOffTip: "Weak signal warning off (this device only)",
    ovrSigTitle: "Signal warning on devices",
    ovrSigShort: "These devices have their own signal warning (set in the device pop-up). Once reset, the global value applies again; when you save.",
    ovrSigEmpty: "None. Own values are set in the device pop-up.",
    ovrSigValue: (v) => `below ${v}`,
    ovrConnTip: (kind, base) => `Connection type set by hand: ${kind} (otherwise ${base})`,
    ovrConnTitle: "Connection type set by hand on devices",
    ovrConnShort: "These devices have a connection type set by hand (in the device pop-up). Once reset, the integration or the detection applies again; when you save.",
    ovrConnEmpty: "None. It is set by hand in the device pop-up.",
    ovrToAuto: "→ automatic",
    ovrResetAll: "Reset all",
    ovrReset: (name) => `Reset: ${name}`,
    ovrUndo: (name) => `Keep: ${name}`,
    ovrOff: "Off",
    ovrToGlobal: "→ global",
    ovrHidden: "hidden",
    devSaveError: "Could not be saved:",
    optNotifyTarget: "Target",
    optNotifyTargetShort: "notify service or entity, e.g. the Companion app.",
    optNotifyTargetInfo:
      "All Device Panel push notifications go to this target; groups (e.g. notify.family) work too. A notify entity only receives title and text, without image and tap target.",
    notifyNone: "No target (no push notifications)",
    notifyEntity: (v) => `${v} (entity)`,
    notifyMissing: (v) => `${v} (not found)`,
    optClick: "Tapping the notification opens",
    optClickShort: "Where tapping a notification about a device leads.",
    clickPanel: "Device in the panel",
    clickDevice: "Home Assistant device page",
    // Monitoring and notifications (since 0.34.0, docs/mockups/notify-v3).
    secMonitor: "Monitoring and notifications",
    sumMonitor: ({ offline, push, delay, battery, batPush, daily }) =>
      `Offline after ${offline} min${push ? `, push after ${delay} min` : ", no push"} · Battery low from ${battery} %${batPush ? (daily ? `, push daily at ${daily}` : ", push right away") : ", no push"}`,
    tabOverview: "Overview",
    tabOutage: "Outage",
    tabBattery: "Battery",
    tabInteg: "Integrations",
    laneOutage: "Outage",
    laneBattery: "Low battery",
    laneEdit: "Change ›",
    tlGone: "device gone",
    tlOffline: "offline in the panel",
    tlPush: "push \"Offline\"",
    tlBoth: "offline and push",
    tlNoPush: "No push",
    tlNoTarget: "no target chosen",
    tlSwitchedOff: "switched off",
    tlIntegOff: "off for the integration",
    tlLow: (pct) => `up to ${pct} %`,
    tlRed: "red in the panel",
    tlInstant: "right away",
    tlInstantSub: "push, once per device",
    tlDaily: (time) => `daily ${time}`,
    tlDailyNew: "push, newly affected",
    tlDailyAll: "push, all low ones",
    tlNote: "Both times count from the start of the outage, they are not added up. \"Offline after\" also applies to the panel; \"Report only after\" cannot be shorter.",
    tlBatNote: "\"Low from\" also applies to the red mark in the panel. Right away: once per device when it drops below. Daily: one summary at the chosen time.",
    delayShort: (min) => `"Report only after" must be at least ${min} min ("Offline after"). Before that a device does not count as offline.`,
    chipPush: "Push",
    chipPersistent: "Persistent",
    chipOnline: "Back online",
    chipGroup: "Group outage",
    diffLabel: "Differs:",
    diffNone: "No exceptions",
    diffInteg: (n) => (n === 1 ? "1 integration" : `${n} integrations`),
    diffDev: (n) => (n === 1 ? "1 device" : `${n} devices`),
    grpDetect: "Detection",
    grpNotify: "Notification",
    grpDiff: "Exceptions",
    grpOutage: "Outage",
    grpBattery: "Battery",
    diffIntegTitle: (n) => (n === 1 ? "1 integration differs" : n ? `${n} integrations differ` : "Integrations"),
    diffIntegGo: "Integrations ›",
    diffIntegNone: "All integrations as set here.",
    noTargetWarn: "Without a target no push is sent. Choose a target: tab \"Overview\".",
    optPersistent: "Persistent notification",
    optBatFields: "Content of the battery notification",
    optBatFieldsShort: "Which details the notification \"Low battery: …\" contains; the device name is in the title.",
    bfBattery: "Level",
    pvBatTitle: (name) => `Low battery: ${name}`,
    pvBatNote: "If more than 3 devices drop below at the same time, or as the daily notification: one summary with name and level per device, the other details in brackets.",
    pvSampleArea: "Hallway",
    pvSampleInteg: "Zigbee",
    integListIntro: "Applies to all devices of the integration; a device can differ in the device pop-up. Hidden integrations are only listed in the section \"Integrations\".",
    filterAll: (n) => `All ${n}`,
    filterOwn: (n) => `Differs ${n}`,
    integNone: "No integrations.",
    integNoneOwn: "No integration differs.",
    integStandard: "Default",
    integUnmon: "Not monitored",
    integDevs: (n, b) => `${n === 1 ? "1 device" : `${n} devices`}${b ? ` · ${b} with battery` : ""}`,
    diffOutage: (after, flags) => (after ? [`Offline after ${after}`, ...flags].join(", ") : `Outage: ${flags.join(", ")}`),
    diffNoPush: "no push",
    diffNoPers: "no persistent",
    diffBattery: (pct, off, noPush) => (off ? "Battery warning off" : pct != null ? `Battery ${pct} %${noPush ? ", no push" : ""}` : "Battery: no push"),
    integBack: "All integrations",
    optMonitor: "Monitor",
    optMonitorShort: "Off: the devices stay in the panel, without outages, battery warning, statistics and notifications.",
    integUnmonInfo: "Not monitored: no outages, no battery warning, no statistics and no notifications. The devices stay in the panel, marked \"Not monitored\". To hide them completely: section \"Integrations\".",
    optPushOutage: "Push on outage",
    optBatPush: "Push on low battery",
    integOffDefault: (v) => `Default (${v})`,
    integBatDefault: (v) => `Default (${v} %)`,
    originOwn: "Own",
    originBatPushOff: "Push off for the integration",
    integPushLater: (v) => `Push only after ${v}: before that a device of this integration does not count as offline.`,
    integPushGlobalOff: "Push on outage is off for all (tab \"Outage\").",
    integBatPushGlobalOff: "Push on low battery is off for all (tab \"Battery\").",
    integDevTitle: "Devices with their own setting",
    ovrKindOffline: (v) => `Offline after ${v}`,
    ovrKindUnmon: "Not monitored",
    ovrKindNotify: "Notifications off",
    ovrKindBattery: (v) => (v === "off" ? "Battery warning off" : `Battery ${v} %`),
    integReset: "All to default",
    integIntroShow: "The panel does not show hidden integrations, and their devices are not monitored.",
    integGoto: "Monitoring and notifications per integration:",
    integGotoLink: "Monitoring and notifications › Integrations",
    secIntegrations: "Integrations",
    secDevices: "Devices in the panel",
    secLook: "Appearance",
    subTypes: "Types",
    subDevs: "Devices",
    subConn: "Connection type",
    subChips: "Filter chips",
    sumConnAuto: "Detected automatically",
    sumConnInteg: (n) => (n === 1 ? "1 integration set" : `${n} integrations set`),
    connIntegTitle: "Connection type per integration",
    connIntegShort: "Applies to all devices of the integration instead of the detection; a connection type set by hand on the device comes first. Applies to all users.",
    connIntegAuto: "Automatic",
    connIntegDevices: (n, detected) => `${n === 1 ? "1 device" : `${n} devices`}${detected ? ` · detected: ${detected}` : ""}`,
    sumDevHidden: (i, t, g) =>
      `${[i && (i === 1 ? "1 integration" : `${i} integrations`), t && (t === 1 ? "1 type" : `${t} types`), g && (g === 1 ? "1 device" : `${g} devices`)].filter(Boolean).join(", ")} hidden`,
    colShow: "Show",
    toggleAll: "Toggle all",
    devicesCount: (n) => (n === 1 ? "1 device" : `${n} devices`),
    hideIntro: "The panel does not show hidden devices, and they are not monitored (no outages, no history).",
    typesIntro: "Change the type of a single device in its pop-up.",
    typesEmpty: "no devices",
    hiddenIntro: "Hidden devices are not in the list and are not monitored (no outages, no notifications). Applies to all users.",
    hiddenEmpty: 'No device is hidden. Hide a device in its pop-up with "Hide device".',
    hiddenShowAll: "Show all",
    hideDevice: "Hide device",
    hiddenToast: (name) => `${name} hidden`,
    shownToast: (name) => `${name} shown again`,
    undo: "Undo",
    hideError: "Could not hide the device:",
    unhideError: "Could not show the device:",
    secUpdates: "Updates",
    sumUpdatesOn: "Daily check · new version under \"Repairs\"",
    sumUpdatesOff: "No automatic check",
    optUpdateCheck: "Check for updates daily",
    optUpdateCheckShort: "Reports a new version under Settings → Repairs.",
    optUpdateCheckInfo:
      "Queries the published releases on GitHub once a day, the first check at a random time 5–65 minutes after startup. Complements HACS, which only checks every few days; turn it off if you don't want the duplicate notice. Pre-releases are never reported there.",
    verName: (v) => `Device Panel ${v}`,
    verCurrent: "Up to date",
    verChecked: (rel) => `last checked ${rel}`,
    verCheck: "Check for updates",
    verChecking: "Checking…",
    verCheckingSub: "Looking for updates…",
    verCheckError: "Check failed:",
    verRateLimit: "GitHub rate limit reached for this internet connection (60 per hour). Try again later.",
    verAvailable: (v) => `Version ${v} available`,
    verBeta: "Beta",
    verInstalled: (v) => `Installed: ${v}`,
    verPreShort: "pre-release",
    verPreToggle: "Show pre-releases",
    verPreToggleShort: "Also offer beta versions for testing. Applies to all users.",
    verPreHint:
      "HACS only installs pre-releases when \"Pre-release\" is switched on for this integration: enable and switch on the \"Pre-release\" entity on the HACS device.",
    verPreHintLink: "Open HACS device",
    verPreHintEnable:
      "HACS only installs pre-releases when \"Pre-release\" is switched on for this integration. The panel can do this for you: it enables the entity in HACS and switches it on. HACS briefly reloads (about 30 seconds). If you later switch \"Show pre-releases\" off, it is switched off again.",
    verPreEnable: "Enable in HACS",
    verPreEnabling: "Enabling … (up to 30 s)",
    verPreEnableError: "Enabling failed:",
    verPreEnableTimeout: "HACS did not provide the entity in time. Please check the HACS device.",
    verInstalledVia: (v, hacs) => `Installed: ${v}${hacs ? " · via HACS" : ""}`,
    verNoHacs: "Install via HACS or manually (see release notes).",
    verReleaseNotes: "Release notes",
    verUpdate: "Update",
    verInstalling: (v) => `Updating to ${v}…`,
    verInstallingSub: "HACS is downloading the new version",
    verInstallError: "Update failed:",
    verHacsSyncing: "Syncing with HACS …",
    verHacsPending:
      "HACS doesn't know this version yet. \"Check for updates\" makes HACS reload its versions; otherwise try again later.",
    verRestartNeeded: (v) => `${v} installed – restart required`,
    verRestartSub: "The new version only becomes active after restarting Home Assistant.",
    verRestart: "Restart now",
    verRestartConfirm: "Restart Home Assistant now? All integrations are briefly unavailable.",
    verRestarting: "Home Assistant is restarting…",
  },
};

export function pickLang(hass) {
  const lang = String((hass && (hass.locale?.language || hass.language)) || "en").toLowerCase();
  return lang === "de" || lang.startsWith("de-") ? "de" : "en";
}
